### ISSUE TITLE
problem with subtitles

### ISSUE THREAD

**Issue by dinhokusanagi** [ThaUnknown/miru#281] opened 2023-05-30 17:26 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

First congratulations on the great app.
Nenum of the anims has subtitles for Brazilian Portuguese

### Proposed Solution

Add torrent sources that have languages ​​from other countries

**Comment by ThaUnknown** [comment] 2023-05-30 17:30
duplicate of https://github.com/ThaUnknown/miru/issues/155

**Closed by ThaUnknown** 2023-05-30 17:30 UTC
Labels: enhancement
