### ISSUE TITLE
[Bug]: Anime disappeared from Your List when finished watching

### ISSUE THREAD

**Issue by muckc** [ThaUnknown/miru#347] opened 2023-10-07 06:19 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.4.12

### What operating system version are you using?

Linux

### Actual Behavior

I don't know if this is a bug or an intended feature, but when I finished watching an anime (even the still airing one), it's just disappear from Your List menu, it's still there in my Anilst favorite tho. I sometimes rewatch some of my favorites so I want to keep them there, or having a Favorite tab would be great.

**Comment by EnergoStalin** [comment] 2023-10-08 00:09
If anime in "WATCHING" or "REPEATING" and there's unwatched episodes it will be in "Continue Watching".

https://github.com/ThaUnknown/miru/blob/916476aeb8c07b5026477bfde089eac53aa015f9/src/renderer/views/Home/Home.svelte#L41

"Your list" displays only planned anime according to this.
https://github.com/ThaUnknown/miru/blob/916476aeb8c07b5026477bfde089eac53aa015f9/src/renderer/views/Home/Home.svelte#L71

Favorite tab would be great but it's a feature request rather bug then.

I think miru is more targeted on ongoings as for now tho.

You can see [Home.svelte](https://github.com/ThaUnknown/miru/blob/916476aeb8c07b5026477bfde089eac53aa015f9/src/renderer/views/Home/Home.svelte#L41) to introspect listing rules

**Comment by muckc** [comment] 2023-10-08 04:36
This is more of a question than a bug report, but still it rather inconvenient to have a seasonal ongoing show to just gone from Your list menu right after I watched the latest episode, less popular show often missing from the Home menu so I have to manually search for them. Will it reappear when new episode become available?

**Comment by EnergoStalin** [comment] 2023-10-08 05:37
> Will it appear when new episode become available?

Yes it appear in "Continue Watching" list. I've got same misunderstanding today but then checked the code you can check #349 for my bad explanation.

Although i agree it's indeed confusing not to have anime in "WATCHING" or similar state somewhere in sight in the app.

**Comment by ThaUnknown** [comment] 2023-10-16 09:20
"your list" only shows you're planning to watch, then once you start watching it, it goes to "continue watching", once you watch it, it doesn't show up on those lists, as there's little reason

later on I'll add a homescreen editor which will allow you to move around lists, and add other statuses from anilist, but this is intended behavior

**Closed by ThaUnknown** 2023-10-16 09:20 UTC
Labels: bug
