### ISSUE TITLE
[Feature Request]: Open anime torrents in preferred media player

### ISSUE THREAD

**Issue by Lonsol** [ThaUnknown/miru#262] opened 2023-04-05 14:45 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I want to be able to watch episodes in my preferred media player. Idk if this is even possible with streaming torrents, but it would be great if so.

### Proposed Solution

Add it as an option in the app settings if possible.

**Comment by ThaUnknown** [comment] 2023-04-05 16:27
duplicate of https://github.com/ThaUnknown/miru/issues/145

**Closed by ThaUnknown** 2023-04-05 16:27 UTC
Labels: enhancement
