### ISSUE TITLE
[Bug]: Miru crashes while navigating the UI

### ISSUE THREAD

**Issue by doc-ar** [ThaUnknown/miru#463] opened 2024-06-30 12:49 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.6

### What operating system version are you using?

Linux

### Expected Behavior

Naviagate the miru UI without any problems

### Actual Behavior

Miru randomly crashes when navigating through UI. The app window completely turns white and then closes. The crash seems to be random and does not always happen with the same UI elements

### Screenshots

I ran miru using the command line and the log is as follows:

```
[user@arch ~]$ miru
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
17:24:25.595 › Checking for update
17:24:43.903 › Update for version 5.1.6 is not available (latest version: 5.1.6, downgrade is disallowed).
17:24:43.906 › checkForUpdatesAndNotify called, downloadPromise is null
[93890:0630/173117.499827:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173118.070385:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[93890:0630/173118.070599:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[93890:0630/173118.071867:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173118.698152:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[93890:0630/173118.698404:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[93890:0630/173118.699820:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173119.342160:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173120.077809:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173120.836173:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173121.488375:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173122.019776:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173122.731838:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[93890:0630/173122.731869:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  miru
```

The log seems to suggest a GPU issue. However I'm using the appropriate intel drivers for my device. I have also tried the flatpak version and this issue occurs in that as well.

**Comment by ThaUnknown** [comment] 2024-06-30 13:22
duplicate of https://github.com/ThaUnknown/miru/issues/436

**Closed by ThaUnknown** 2024-06-30 13:22 UTC
Labels: bug
