### ISSUE TITLE
[Bug]: Doesn't record progress watched Episodes

### ISSUE THREAD

**Issue by iVolgin69** [ThaUnknown/miru#455] opened 2024-05-19 12:40 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.0

### What operating system version are you using?

Windows

### Expected Behavior

That it should record my progress to the last episode seen.

### Actual Behavior

The problems seems to occur when using the "next episode" keybind, it just records the first Ep I clicked on when I started watching, not the last episode seen.

(P:S I'm watching 90% of the Episode then skipping the ending and watching the next, maybe that's why it does'nt register)

A manual workaround I have found, is listing the EP im at on AniList.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/116735161/c15e13f7-3dac-4376-911e-f76154e345cd)

As you can see I'm currently on episode 38, however it only recorded 30 (the first one I began watching).

You will also notice that it's showing as ep 30 on the player, (aswell as on discord)

**Comment by ThaUnknown** [comment] 2024-07-26 12:08
duplicate of #257

**Closed by ThaUnknown** 2024-07-26 12:08 UTC
Labels: bug
