### ISSUE TITLE
Close player completely

### ISSUE THREAD

**Issue by datogoglidze** [ThaUnknown/miru#117] opened 2022-03-19 23:24 UTC
**Is your feature request related to a problem? Please describe.**
Can't turn off video player. I can click home button but video goes in picutire-in-picture mode.

**Describe the solution you'd like**
"X" button for only video player. Not for the whole app.

**Additional context**
Screenshots:
![Untitled2](https://user-images.githubusercontent.com/70262653/159141728-116d4d7c-f68f-4bae-8b56-5ec55780d511.png)
![Untitled](https://user-images.githubusercontent.com/70262653/159141729-562299ea-77a3-4686-bbbb-2e05f47f5dbc.png)

**Comment by ThaUnknown** [comment] 2022-03-20 03:11
duplicate of https://github.com/ThaUnknown/miru/issues/108

**Closed by ThaUnknown** 2022-03-20 03:11 UTC
Labels: enhancement
