### ISSUE TITLE
[Bug]: miru for deb and Appimage does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by dnet890** [ThaUnknown/miru#516] opened 2024-08-29 02:32 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.5.6

### What operating system version are you using?

Linux

### Expected Behavior

it should run

### Actual Behavior

it does not run

### Screenshots

<img width="873" alt="2024-08-29_11-29" src="https://github.com/user-attachments/assets/6097b8e6-1ac8-48e5-8620-646510824e89">

**Comment by ThaUnknown** [comment] 2024-08-31 16:17
duplicate of https://github.com/ThaUnknown/miru/issues/436

**Closed by ThaUnknown** 2024-08-31 16:17 UTC
Labels: bug
