### ISSUE TITLE
[Bug]: APPIMAGE env is not defined

### ISSUE THREAD

**Issue by Wiz1991** [ThaUnknown/miru#196] opened 2022-07-07 18:47 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v2.9.1

### What operating system version are you using?

Linux

### Expected Behavior

The app should open 

### Actual Behavior

Opening the app via desktop entry results in a crash/error report 1-2 minutes later. Opening the app manually via CLI shows the following error: 
```
APPIMAGE env is not defined, current application is not an AppImage
```

The app was installed via .deb
Using the AppImage build, it works as expected. 

### Screenshots

![image](https://user-images.githubusercontent.com/45233935/177847709-fddffb4c-058c-417e-bc9e-8e65931689e7.png)

**Comment by Muril-o** [comment] 2022-07-08 00:05
So the app works just fine and you're just bothered with a debug message? Or the app is consistently crashing 1-2 minutes after launch?

If the first, that message is to be expected from electron since [.deb isn't a supported updatable target](https://www.electron.build/auto-update.html#auto-updatable-targets) (and it really should never be!).

If the second (and I'd assume it to be the second since you labeled it as a bug), I cannot reproduce it on Ubuntu 22.04 LTS, Xubuntu 22.04 LTS or Debian Testing. Which would require more info like your current distro and linux setup so I could try to reproduce it and work on a fix for whatever problem it is, which still is most likely not to be an issue with miru since you mentioned the appimage works just fine.

**Comment by Wiz1991** [comment] 2022-07-08 07:07
No no, its not a debug message, its what it crashes with. It wont even launch because of that. 

I had a v2.4.2 installed and treid updating. After updating it wouldnt launch anymore. I did a clean install (wiped everything beforehand)  of the latest version with the .deb and it would not launch again, after launching manually via cli that was the error i got. I uninstalled everything again and tried the AppImage, which worked fine.

**Comment by Muril-o** [comment] 2022-07-08 11:14
Try installing [this](https://github.com/Muril-o/miru/releases/download/v0.6.0/linux-amd64-Miru-2.9.1-alpha-test.deb). I removed the update check for non-appimage linux. Does it still crash?

**Comment by ThaUnknown** [comment] 2022-07-15 15:45
linux issues are eeeeeeh

I won't bother solving this, since I have no clue how to, and very little interest in linux overall, Miru works on linux, and any subsequent issues are because of the user or his dist, so I'll likely close this soon as I have no idea what the issue even is

**Closed** 2022-07-16 05:34 UTC
Labels: bug, wontfix

**Comment by Ate329** [comment] 2024-04-23 19:52
I had the same error report because I added these two global flags in .config/electron-flags.conf and then I commented them everything just works as normal. So it can be caused if you added some flags in the line for Exec in the miru.desktop file
I hope this might help but I might not be caused by the same thing.
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```
