### ISSUE TITLE
[Bug]: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by idklevi** [ThaUnknown/miru#496] opened 2024-08-14 08:34 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.2.16

### What operating system version are you using?

Windows

### Actual Behavior

this happened when i updated to the latest version
A JavaScript error occurred in the main process
TypeError: Object has been destroyed at App. <anonymous> (C:\Program Files\Miru\resources\app.asar\build\main.js:2:5246) at App.emit (node:events:514:28)

### Screenshots

![Screenshot 2024-08-14 135914](https://github.com/user-attachments/assets/5ee36a60-a85c-4847-b469-e40cf141f314)

**Comment by PrimeTwister** [comment] 2024-08-14 09:11
same here

**Comment by ThaUnknown** [comment] 2024-08-14 09:16
duplicate of https://github.com/ThaUnknown/miru/issues/495

close the app using the update button in the bottom left of the app, rather than close, this is fixed in later versions

you might need to kill miru in the task manager first

**Closed by ThaUnknown** 2024-08-14 09:16 UTC
Labels: bug
