### ISSUE TITLE
[Feature Request]: adding custom hotkeys

### ISSUE THREAD

**Issue by SuckyBuckyYT** [ThaUnknown/miru#437] opened 2024-03-27 16:50 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

the 2 second forward and back from left and right keys are not enough

### Proposed Solution

make it that i can set 5 seconds or 10 seconds

**Comment by ThaUnknown** [comment] 2024-03-27 16:54
duplicate of #266

**Closed by ThaUnknown** 2024-03-27 16:54 UTC
Labels: enhancement
