### ISSUE TITLE
[Bug]: Arch and AppImage versions try to update using deb

### ISSUE THREAD

**Issue by Jeremi360** [ThaUnknown/miru#340] opened 2023-09-13 10:11 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.4.1-1 - the newest in AUR repos

### What operating system version are you using?

Linux

### Expected Behavior

When I run miru AUR or AppImage versions it try to update it using deb:
```
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
12:07:56.838 › Checking for update
12:07:57.973 › Found version 4.4.7 (url: linux-Miru-4.4.7.AppImage, linux-Miru-4.4.7.deb)
12:07:57.974 › Downloading update from linux-Miru-4.4.7.AppImage, linux-Miru-4.4.7.deb
12:07:57.975 › updater cache dir: /home/jeremi360/.cache/miru-updater
12:07:58.200 › Update has already been downloaded to /home/jeremi360/.cache/miru-updater/pending/linux-Miru-4.4.7.deb).
12:08:04.805 › Auto install update on quit
12:08:04.806 › Install: isSilent: true, isForceRunAfter: false
12:08:04.806 › Executing: which gksudo || which kdesudo || which pkexec || which beesu with args: 
which: no gksudo in (/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no kdesudo in (/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
/usr/bin/pkexec
12:08:04.826 › Error: TypeError: Cannot read properties of null (reading 'trim')
    at n.spawnSyncLog (/opt/Miru/resources/app.asar/build/main.js:2:116811)
    at n.wrapSudo (/opt/Miru/resources/app.asar/build/main.js:2:116377)
    at n.doInstall (/opt/Miru/resources/app.asar/build/main.js:2:117707)
    at n.install (/opt/Miru/resources/app.asar/build/main.js:2:115608)
    at /opt/Miru/resources/app.asar/build/main.js:2:116070
    at App.<anonymous> (/opt/Miru/resources/app.asar/build/main.js:2:121832)
    at Object.onceWrapper (node:events:628:26)
    at App.emit (node:events:525:35)

```

### Actual Behavior

It shouldn't try to install deb version in AUR and AppImage version

**Comment by ThaUnknown** [comment] 2023-09-13 12:32
duplicate of #308

**Closed by ThaUnknown** 2023-09-13 12:32 UTC
Labels: bug
