### ISSUE TITLE
No audio being played from certain sources

### ISSUE THREAD

**Issue by Star3161** [ThaUnknown/miru#115] opened 2022-03-19 14:30 UTC
**Describe the bug**
When playing certain sources there is no audio present. Subtitles and video is shown and playing normally. 
Confirmed files with no audio:
- [SubsPlease] (480p, 720p, 1080p) Komi Can't Communicate.  (Audio is present in the another source from NovaWorks.) 
- [DucksterPS] Violet Evergarden - The Movie. 
- [Eraw-raws] Fate Extra - Last Encore - 01 [720p] [Multi Sub].

**To Reproduce**
Load and play any of the files listed above. 

**Expected behavior**
Audio should be present upon the episode loading and playing. 

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 21H2 Build 22000.556
 - v0.10.1

**Additional Info**
RSS (Auto-Play torrents, Trusted Only and Batch Lookup) & Torrent (Persist Files, Disable DHT and PeX) settings are all unchecked.

**Comment by ThaUnknown** [comment] 2022-03-19 15:00
audio codec is not supported by the electron build, duplicate of #95

**Closed by ThaUnknown** 2022-03-19 15:00 UTC
Labels: bug
