### ISSUE TITLE
[Bug]: Application crashes when trying to open the settings panel

### ISSUE THREAD

**Issue by soupertonic** [ThaUnknown/miru#254] opened 2023-02-05 14:20 UTC
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

3.7.2

### What operating system version are you using?

MacOS

### Expected Behavior

Being able to review audio settings because some audio codec problems.

### Actual Behavior

The application crashes instantly when trying to access the settings panel from the entry view or while video playback.

### Screenshots

<img width="479" alt="Screenshot 2023-02-05 at 15 19 13" src="https://user-images.githubusercontent.com/64563583/216824888-a80749b0-5e26-420c-aaf2-7c28a3d4a6b7.png">

[Show Details output](https://gist.githubusercontent.com/soupertonic/693858963f69cd3e37c5c40cb8918aed/raw/a07448511a14a0bd7e852add2db3a3cb817ae195/report.txt)

**Comment by soupertonic** [comment] 2023-02-05 14:29
3.5.0 is working as expected. So it seems this regression was introduced in the newer releases.

**Comment by ThaUnknown** [comment] 2023-02-05 14:30
so i assume 3.5.2 is where it crashes? great that means macos doesn't support styling AOT elements

**Comment by soupertonic** [comment] 2023-02-05 14:34
Did test 3.5.2. Crashed.

**Comment by ThaUnknown** [comment] 2023-02-05 15:26
try the latest beta if that doesn't fix it then idk, just MacOS things, because the thing that crashes macos works fine both on linux windows and android lol

**Comment by ThaUnknown** [comment] 2023-02-05 18:29
this was confirmed fixed in the beta by other macos users

**Closed by ThaUnknown** 2023-02-05 18:29 UTC
Labels: bug, external
