### ISSUE TITLE
Subtitles intermittently disappearing

### ISSUE THREAD

**Issue by oelow** [ThaUnknown/miru#112] opened 2022-03-18 01:35 UTC
**Describe the bug**
While watching an episode subtitles will randomly at times stop showing up during dialogue and reappear after some time.

**To Reproduce**
Open up any episode and watch for a short period of time until subtitles disappear.

**Expected behavior**
Subtitles should follow dialogue between characters and not drop out during some sentences.

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 21H2 Build 22000.556
 - Version: Tried on both version 0.6.0 and 0.6.4

**Additional context**
I have only used the app to watch anime twice and on the first occurrence was during Attack on Titan's final season part 2 episode 10 on version 0.6.0 of the app. I noticed multiple segments where the subtitles would drop off and after some time would reappear. The next time I tried testing it on version 0.6.4 of the app by watching an episode of My dress-up darling episode 1 and paused the episode at the beginning in hopes of letting it download properly, but still experienced a few times where subtitles dropped out again but not as often as on 0.6.0.

**Comment by ThaUnknown** [comment] 2022-03-18 01:38
this is a known issue with the parser that occurs when your internet connection can't match that of video bitrate, what ends up happening is the video makes another stream request, ditches the old one which causes a single subtitle cue to get omitted

**Comment by ThaUnknown** [comment] 2022-03-18 01:40
I'll attempt to fix this after #103 is resolved

**Comment by Muril-o** [comment] 2022-03-18 13:41
Could reproduce this on `[Erai-raws] Jujutsu Kaisen - 06 [1080p HEVC][Multiple Subtitle].mkv 17:10 17:22` local persisted file.

`[matroska-subtitles] EBML stream decoding error subtitle-stream.js:49`

```
Uncaught TypeError: Failed to execute 'close' on 'ReadableStreamDefaultController': Cannot close an errored readable stream
    at MessagePort.<anonymous>
``` [(sw.js:57:24)](https://github.com/ThaUnknown/miru/blob/574cc098606f0499c9512f0a61ef3e75160c4c83/src/renderer/public/sw.js#L57)

Registering this here for future reference to check if its fixed or a new bug.

**Comment by ThaUnknown** [comment] 2022-03-18 13:46
this happens because the stream is prematurely closed or because it pushed null, it's intentional to prevent ram leaks, but it's possible it happens when not intended, will debug

**Comment by rubanunes** [comment] 2022-03-21 19:14
Don't know if it helps but the issue only appears to me when using the next episode function or when skipping the opening. Because if it happens I just restart the app and it's fine

**Comment by ThaUnknown** [comment] 2022-03-21 19:21
> Don't know if it helps but the issue only appears to me when using the next episode function or when skipping the opening. Because if it happens I just restart the app and it's fine

just a coincidence

**Comment by ThaUnknown** [comment] 2022-03-22 15:57
I figured out why this wasn't an issue in my browser version, I cache 1 chunk ahead which forces the parsing of partial subtitle cues, which would otherwise be cut, so the solution for this is to: create a passthrough or even a async iterator, which caches 1-2 chunks ahead and the chunks which are caches would be pulled tru the EBML parser, essentially always caching&parsing 2 chunks ahead, then when a port re-opens after closing/cutting off it will actually be behind what was pulled by the caching iterator and the cues will overlap preventing loss

**Comment by ThaUnknown** [comment] 2022-03-24 18:31
I've added some patches in https://github.com/ThaUnknown/miru/commit/dc813fcdf932db722f71c380b376766aa4de754d to mitigate this a bit, but those are still just patches, the underlying issue is not fixed, and I will not attempt to fix it until the IPC re-write because of bugs caused by electrons node integration

**Comment by ThaUnknown** [comment] 2022-04-02 15:50
95e8c8e6cb66508a82edc17897e6c3412f98ff4b

**Comment by ThaUnknown** [comment] 2022-04-02 16:31
@oelow please try reproducing the issue on 1.0.1, I believe it was fixed however thanks to the HTTP server implementation which closes streams, without me having to patch stream closing by hand

**Comment by ThaUnknown** [comment] 2022-04-04 14:55
I can no longer reproduce the issue, except for when seeking onto a cue, but all video players have that issue. I'm gonna mark this as fixed, ping me here if the issue persists
https://github.com/ThaUnknown/miru/commit/ac265701179f4eff171fa449bb05ead6bcc91564

**Closed by ThaUnknown** 2022-04-04 14:55 UTC
Labels: bug, good first issue, testing
